version: '3.7'


services:
  nginx:
    image: nginx:1.21.6
    network_mode: service:wireguard
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  wireguard:
    image: linuxserver/wireguard
    volumes:
      - './wireguard:/config'
      # - '/lib/modules:/lib/modules:ro'
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1

  ubuntu:
    image: curlimages/curl
    depends_on:
      - wireguard
    # network_mode: service:wireguard
    # entrypoint: /bin/sh -c 'echo 123 && sleep 2 && echo 45 && curl "http://10.128.0.117:8080/v2/management/user-profile-summary/user_profiles?root=content&company_uuid=7949d219-86f9-48f5-a5f8-ec7677fe39f4&only_uuids=true&requested_by=3b7fe3c9-3c28-48fd-8779-26c6b614a7e2"'
    # entrypoint: /bin/sh -c 'echo 123 && sleep 2 && echo 45 && curl "http://wireguard/nginx.conf"'
    entrypoint: /bin/sh -c 'echo 123 && sleep 1 && echo 45 && curl "http://wireguard/v2/management/user-profile-summary/user_profiles?root=content&company_uuid=7949d219-86f9-48f5-a5f8-ec7677fe39f4&only_uuids=true&requested_by=3b7fe3c9-3c28-48fd-8779-26c6b614a7e2"'
    # entrypoint: /bin/sh -c 'echo 123 && sleep 2 && echo 45 && curl "http://wireguard/v2/management/user-profile-summary/user_profiles?root=content&company_uuid=7949d219-86f9-48f5-a5f8-ec7677fe39f4&only_uuids=true&requested_by=3b7fe3c9-3c28-48fd-8779-26c6b614a7e2"'
